include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    close_sinks: warning

linter:
  rules:
    avoid_dynamic_calls: false
    avoid_empty_else: true
    # Would require the @immutable annotation to be consistently and
    # correctly used everywhere.
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_positional_boolean_parameters: true
    avoid_returning_null_for_future: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_type_to_string: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    always_use_package_imports: false
    always_declare_return_types: false
    camel_case_types: true
    cascade_invocations: true
    close_sinks: true
    # Missing deprecated annotation.
    deprecated_consistency: true
    # DO reference all public properties in debug methods.
    diagnostic_describe_all_properties: false
    # Avoid empty statements.
    empty_statements: true
    # Define case clauses for all constants in enum-like classes.
    exhaustive_cases: true
    # Always override hashCode if overriding ==.
    hash_and_equals: true
    # Don't import implementation files from another package.
    implementation_imports: true
    # Invocation of Iterable.contains with references of unrelated types.
    iterable_contains_unrelated_type: true
    # Avoid calling toString() on runtimeType.
    no_runtimeType_toString: true
    # Only throw instances of classes extending either Exception or Error.
    only_throw_errors: true
    prefer_asserts_in_initializer_lists: true
    prefer_const_constructors: false
    prefer_final_in_for_each: true
    prefer_final_locals: false
    prefer_foreach: true
    prefer_void_to_null: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_is_not_operator: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    public_member_api_docs: false
    sized_box_for_whitespace: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_final: false
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    # Avoid using unnecessary statements.
    unnecessary_statements: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
